matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
        - MINIKUBE_MEMORY=7777
# Possible os x support in the future
    #- os: osx
    #  osx_image: xcode7.2

language: bash

addons:
  apt:
    packages:
      - curl
      - socat
      - time

before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travis/ubuntu-compile-nsenter.sh && sudo cp .tmp/util-linux-2.30.2/nsenter /usr/bin; fi
# Possible os x support in the future
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

script:
# /bin/sh points to dash on trusty, which can cause some of the tests to fail
  - ls -alh `which sh`
  - /usr/bin/time -v make fedora.done
  - /usr/bin/time -v make xenial.done
    #- /usr/bin/time -v make trusty.done
    #- /usr/bin/time -v make stretch.done
    #- /usr/bin/time -v make zesty.done
    #- /usr/bin/time -v make artful.done
