matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
        - MINIKUBE_MEMORY=7777
    - os: osx
      osx_image: xcode7.2

language: bash

addons:
  apt:
    packages:
      - curl
      - socat
      - time

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash .ci/linux_before_install.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .ci/osx_before_install.sh; fi

script:
# /bin/sh points to dash on trusty, which can cause some of the tests to fail
  - ls -alh `which sh`
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /usr/bin/time -v make fedora.done;  fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /usr/bin/time -v make stretch.done; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /usr/bin/time -v make xenial.done;  fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /usr/bin/time -v make centos7.done; fi
  - bash rxNstall
  - bash test
