matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env:
        - TOOL_NODE_FLAGS="--max-old-space-size=2048"
        - FIX_DOTFILES="true"
      cache:
        directories:
        - $HOME/.nvm
        - $HOME/.meteor
        - $HOME/reaction
    - os: osx
      osx_image: xcode7.2
      env:
        - TOOL_NODE_FLAGS="--max-old-space-size=2048"
        - FIX_NVM_PREFIX="true"
        - FIX_DOTFILES="true"
      cache:
        directories:
        - $HOME/.nvm
        - $HOME/.meteor
        - $HOME/reaction

language: bash

addons:
  apt:
    packages:
      - curl
      - socat
      - time
      - wget
      - tar
      - ca-certificates
      - nodejs
      - npm

before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash .ci/linux_before_install.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash .ci/rmdotfiles.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .ci/osx_before_install.sh; fi

script:
  - bash rxNstall
  - bash .ci/test.sh
  - touch ~/.bashrc ~/.bash_profile ~/.zshrc ~/.profile
  - echo '# bashrc'; cat ~/.bashrc
  - echo '# zshrc'; cat ~/.zshrc
  - echo '# bash_profile'; cat ~/.bash_profile
  - echo '# profile'; cat ~/.profile
