matrix:
  include:
    - os: osx
      osx_image: xcode7.2
      env:
        - TOOL_NODE_FLAGS="--max-old-space-size=2048"

language: bash

addons:
  apt:
    packages:
      - curl
      - socat
      - time

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .ci/osx_before_install.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then bash rxNstall; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then bash test; fi
  - touch .bashrc .bash_profile .zshrc .profile
  - echo '# bashrc'; cat .bashrc
  - echo '# zshrc'; cat .zshrc
  - echo '# bash_profile'; cat .bash_profile
  - echo '# profile'; cat .profile
