#!/bin/bash
TMP_DIR=$(mktemp -d --suffix='.reactioNstall.tmp' 2>/dev/null || mktemp -d -t '.reactioNstall.tmp')
METEOR_VERSION=${METEOR_VERSION:-1.6.0.1}

backup_bashrc () {
  mv $HOME/.bashrc $TMP_DIR/
  touch ~/.bashrc
}

restore_bashrc () {
  cat $TMP_DIR/.bashrc >> $HOME/.bashrc
}

killtmp () {
  cd
#  restore_bashrc
  rm -Rf $TMP_DIR
}
trap killtmp EXIT

# Check if a command exists
check_cmd () {
  if ! type "$1" > /dev/null; then
    errror
    echo "$1 was not found in your path!"
    echo "To proceed please install $1 to your path and try again!"
    exit 1
  fi
}

chkdir () {
  if [ ! -w $1 ] ; then
    sudo mkdir -p $1
    sudo chown $USER. $1
  fi
  if [ ! -w $1 ] ; then
    errror
    echo "Cannot write to $1, please check your permissions"
    exit 2
  fi
}

reaction_full_test () {
cd $TMP_DIR
reaction help
echo init reaction
reaction init
cd reaction
echo test reaction
reaction test
cd
}


LINE_TO_ADD='eval `keychain --agents "gpg,ssh" --dir ~/.ssh/keychain --eval id_rsa id_dsa id_ecdsa 4157F971`'
ZSHRC_LOCATION=~/.zshrc
BASHRC_LOCATION=~/.bashrc
BASH_PROFILE_LOCATION=~/.bash_profile
PROFILE_LOCATION=~/.profile

check_if_line_exists_zshrc()
{
    grep -qsFx "$LINE_TO_ADD" $ZSHRC_LOCATION
}

add_line_to_zshrc()
{
  TARGET_FILE=$ZSHRC_LOCATION
    [ -w "$TARGET_FILE" ] || TARGET_FILE=$ZSHRC_LOCATION
    printf "%s\n" "$LINE_TO_ADD" >> "$TARGET_FILE"
}

check_if_line_exists_bashrc()
{
    grep -qsFx "$LINE_TO_ADD" $BASHRC_LOCATION
}

add_line_to_bashrc()
{
  TARGET_FILE=$BASHRC_LOCATION
    [ -w "$TARGET_FILE" ] || TARGET_FILE=$BASHRC_LOCATION
    printf "%s\n" "$LINE_TO_ADD" >> "$TARGET_FILE"
}

check_if_line_exists_bash_profile()
{
    grep -qsFx "$LINE_TO_ADD" $BASH_PROFILE_LOCATION
}

add_line_to_bash_profile()
{
  TARGET_FILE=$BASH_PROFILE_LOCATION
    [ -w "$TARGET_FILE" ] || TARGET_FILE=$BASH_PROFILE_LOCATION
    printf "%s\n" "$LINE_TO_ADD" >> "$TARGET_FILE"
}

check_if_line_exists_profile()
{
    grep -qsFx "$LINE_TO_ADD" $PROFILE_LOCATION
}

add_line_to_profile()
{
  TARGET_FILE=$PROFILE_LOCATION
    [ -w "$TARGET_FILE" ] || TARGET_FILE=$PROFILE_LOCATION
    printf "%s\n" "$LINE_TO_ADD" >> "$TARGET_FILE"
}

install_nvm () {
  echo "installing nvm"
  touch ~/.bash_profile
  wget https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh
  ls -lh install.sh
  cat install.sh
  bash install.sh
  curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash

}

install_meteor () {
  #curl --silent -L https://raw.githubusercontent.com/reactioncommerce/base/master/scripts/install-meteor.sh | bash -l
  curl --silent https://install.meteor.com/ | sh
  LINE_TO_ADD='export PATH=~/.meteor:$PATH'
  check_if_line_exists_zshrc || add_line_to_zshrc
  check_if_line_exists_bash_profile || add_line_to_bash_profile
}

lts_install () {
  bash -l -c 'command -v nvm'
  echo "Engage nvm to install lts/carbon"
  bash -l -c 'nvm install --lts'
  echo "Engage nvm to alias lts/carbon to default"
  bash -l -c 'nvm alias default lts/carbon'
}

reaction_install () {
  install_meteor
  source ~/.bash_profile

  check_cmd npm
  check_cmd node
  chkdir $HOME/.nvm

  echo -n 'npm version: '
  npm -v
  echo -n 'node version: '
  node -v

  echo 'Installing reaction-cli'
  npm i -g reaction-cli
  echo 'reaction-cli has been installed...'
}

dotfiles_install () {
  touch ~/.zshrc
  touch ~/.bashrc
  touch ~/.bash_profile
  LINE_TO_ADD='export NVM_DIR=~/.nvm'
  check_if_line_exists_zshrc || add_line_to_zshrc
  check_if_line_exists_bash_profile || add_line_to_bash_profile

  LINE_TO_ADD='source ~/.nvm/nvm.sh'
  check_if_line_exists_zshrc || add_line_to_zshrc
  check_if_line_exists_bash_profile || add_line_to_bash_profile
  LINE_TO_ADD='source ~/.bash_profile'
  check_if_line_exists_bashrc || add_line_to_bashrc
  LINE_TO_ADD='source ~/.bash_profile'
  check_if_line_exists_profile || add_line_to_profile
}

osx_install () {
  echo "Installing NVM on OSX"

  install_nvm

  dotfiles_install

  source ~/.bash_profile
  npm config delete prefix
  lts_install
  source ~/.bash_profile

  reaction_install
}

linux_install () {
  echo "Installing NVM on Linux"

  install_nvm

  dotfiles_install

  source ~/.bash_profile
  lts_install
  source ~/.bash_profile

  reaction_install
}

# taking some cues directly from the meteor install script

# We wrap this whole script in a function, so that we won't execute
# until the entire script is downloaded.
# That's good because it prevents our output overlapping with curl's.
# It also means that we can't run a partially downloaded script.
# We don't indent because it would be really confusing with the heredocs.
run_it () {

# Now, on to the actual installer!

## NOTE sh NOT bash. This script should be POSIX sh only, since we don't
## know what shell the user has. Debian uses 'dash' for 'sh', for
## example.

set -e
set -u

# Let's display everything on stderr.
exec 1>&2

UNAME=$(uname)

if [ "$UNAME" = "CYGWIN_NT-10.0" ] ; then
  check_cmd choco
  check_cmd helm
  PLATFORM="os.cygwin.x86_64"
  echo "WARNING: Cygwin is not supported for this installer at this time!"
  exit 1
fi

if [ "$UNAME" == "Linux" -o "$UNAME" == "Darwin" ] ; then
  echo " $UNAME is a Supported OS"
elif [ "$UNAME" ">" "MINGW" -a "$UNAME" "<" "MINGX" ] ; then
  echo " $UNAME is a Supported OS"
else
  echo " $UNAME is not a Supported OS"
  echo "Sorry, this OS is not supported yet via this installer."
  exit 1
fi

# Check to see if it starts with MINGW.
if [ "$UNAME" ">" "MINGW" -a "$UNAME" "<" "MINGX" ] ; then
  check_cmd choco
  check_cmd helm
  PLATFORM="os.windows.x86_64"
  echo "WARNING: Windows is experimental for this installer at this time!"
fi

if [ "$UNAME" = "Darwin" ] ; then
  check_cmd brew
  ### OSX ###
  if [ "i386" != "$(uname -p)" -o "1" != "$(sysctl -n hw.cpu64bit_capable 2>/dev/null || echo 0)" ] ; then
    # Can't just test uname -m = x86_64, because Snow Leopard can
    # return other values.
    echo "Only 64-bit Intel processors are supported at this time in OSX."
    exit 1
  fi

  PLATFORM="os.osx.x86_64"
  echo "WARNING: OSX is experimental for this installer at this time!"
elif [ "$UNAME" = "Linux" ] ; then
  ### Linux ###
  LINUX_ARCH=$(uname -m)
  if [ "${LINUX_ARCH}" = "x86_64" ] ; then
    PLATFORM="os.linux.x86_64"
  else
    echo "Unusable architecture: ${LINUX_ARCH}"
    echo "ReactioNstall only supports x86_64 for now."
    exit 1
  fi
fi


# make reqs
if [ "$PLATFORM" = "os.linux.x86_64" ] ; then
  echo linux
  linux_install
elif [ "$PLATFORM" = "os.osx.x86_64" ] ; then
  echo osx
  osx_install
elif [ "$PLATFORM" = "os.windows.x86_64" ] ; then
  echo windows is not support yet
  exit 1
fi

#reaction_full_test
echo 'rxNstall has finished'

# End run it wrapper
}

check_cmd mktemp
check_cmd git
check_cmd curl
check_cmd uname
check_cmd 'grep'
check_cmd 'sed'


run_it
