#!/bin/bash -l

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

echo test
TMP_DIR=$(mktemp -d --suffix='.reactioNstall.tmp' 2>/dev/null || mktemp -d -t '.reactioNstall.tmp')

killtmp () {
  cd
#  restore_bashrc
  rm -Rf $TMP_DIR
}

trap killtmp EXIT
cd $TMP_DIR

reaction help
reaction -v
#echo init reaction
#reaction init
#cd reaction
#echo test reaction
#reaction test
#cd
which node
which npm
echo 'end tests'
