#!/bin/bash -l
PATH=~/.meteor:$PATH
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

echo test
TMP_DIR=$(mktemp -d --suffix='.reactioNstall.tmp' 2>/dev/null || mktemp -d -t '.reactioNstall.tmp')

killtmp () {
  cd
#  restore_bashrc
  rm -Rf $TMP_DIR
}

trap killtmp EXIT
cd $TMP_DIR

reaction help
#echo init reaction
#reaction init
#cd reaction
#echo test reaction
#reaction test
#cd
cd $HOME
echo ''
echo -n 'Which node:'
which node
echo -n 'Which NPM: '
which npm
echo -n 'Which meteor: '
which meteor
echo ''
echo 'Inside the meteor directory:'
ls -lh .meteor
echo ''
echo -n 'Reaction version:'
reaction -v
which reaction
echo ''
if [ "$REACTION_FULL_TEST" = "true" ]; then
  if [ ! -d "$HOME/reaction/.git" ]; then
    mv reaction reaction-`date -I`
    reaction init
  else
    ls -lh $HOME/reaction
  fi
  cd $HOME/reaction
  reaction pull
  reaction --version
fi
echo ''
echo 'end tests'
