version: 2

jobs:
  build:
    machine: true
    environment:
      MINIKUBE_OPTS: "--vm-driver=none"
    steps:
      - checkout

      - run: sudo bash .ci/linux_before_install.sh

      - run: /usr/bin/time -v make trusty

      - run: /usr/bin/time -v make xenial

      - run: /usr/bin/time -v make zesty

      - run: /usr/bin/time -v make artful
