version: 2

jobs:
  build:
    machine: true
    environment:
      TOOL_NODE_FLAGS: "--max-old-space-size=2048"
    steps:
      - checkout

      - run: sudo bash .ci/linux_before_install.sh

      - run: /usr/bin/time -v make trusty

      - run: /usr/bin/time -v make xenial

      - run: /usr/bin/time -v make zesty

      - run: /usr/bin/time -v make artful
