version: 2

jobs:
  build:
    machine: true
    environment:
      MINIKUBE_OPTS: "--vm-driver=none"
    steps:
      - checkout

      - run: sudo bash .ci/linux_before_install.sh

      - run: bash rxNstall
