version: 2

jobs:
  build:
    machine: true
    environment:
      MINIKUBE_OPTS: "--vm-driver=none"
    steps:
      - checkout

      - run: .circleci/install.sh

      - run: /usr/bin/time -v make fedora.done

      - run: /usr/bin/time -v make centos7.done

      - run: /usr/bin/time -v make tumbleweed.done
