#!/bin/bash
BRANCHES='archlinux centos debian fedora gentoo macosx opensuse ubuntu'
echo 'Propagator'

echo $BRANCHES |tr ' ' '\n'| xargs -n1 -I{} bash -c "git checkout {} ; scripts/mergewmaster ; git commit -am mergewmaster"
